<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="Aspire.Npgsql.EntityFrameworkCore.PostgreSQL" Version="9.4.2" />
    <PackageVersion Include="Aspire.Hosting.AppHost" Version="9.4.2" />
    <PackageVersion Include="Aspire.Hosting.PostgreSQL" Version="9.4.2" />
    <PackageVersion Include="AutoMapper" Version="13.0.1" />
    <PackageVersion Include="CommunityToolkit.Aspire.Hosting.MailPit" Version="9.7.2" />
    <PackageVersion Include="CommunityToolkit.Aspire.Hosting.McpInspector" Version="9.8.0" />
    <PackageVersion Include="FluentValidation.DependencyInjectionExtensions" Version="12.0.0" />
    <PackageVersion Include="IdentityModel" Version="7.0.0" />
    <PackageVersion Include="MailKit" Version="4.13.0" />
    <PackageVersion Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="9.0.9" />
    <PackageVersion Include="Microsoft.AspNetCore.Authentication.OpenIdConnect" Version="9.0.9" />
    <PackageVersion Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.7" />
    <PackageVersion Include="Microsoft.Extensions.Configuration.Binder" Version="9.0.9" />
    <PackageVersion Include="Microsoft.Extensions.Diagnostics.HealthChecks" Version="9.0.9" />
    <PackageVersion Include="Microsoft.Extensions.Diagnostics.HealthChecks.EntityFrameworkCore" Version="8.0.6" />
    <PackageVersion Include="Microsoft.Extensions.Hosting.Abstractions" Version="9.0.9" />
    <PackageVersion Include="Microsoft.Extensions.Http.Resilience" Version="9.9.0" />
    <PackageVersion Include="Microsoft.Extensions.Logging.Abstractions" Version="9.0.9" />
    <PackageVersion Include="Microsoft.Extensions.Resilience" Version="9.9.0" />
    <PackageVersion Include="Microsoft.Extensions.ServiceDiscovery" Version="9.4.2" />
    <PackageVersion Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="9.0.0" />
    <PackageVersion Include="ModelContextProtocol.AspNetCore" Version="1.0.0-rc.1" />
    <PackageVersion Include="OpenTelemetry.Exporter.OpenTelemetryProtocol" Version="1.12.0" />
    <PackageVersion Include="OpenTelemetry.Extensions.Hosting" Version="1.12.0" />
    <PackageVersion Include="OpenTelemetry.Instrumentation.AspNetCore" Version="1.12.0" />
    <PackageVersion Include="OpenTelemetry.Instrumentation.EntityFrameworkCore" Version="1.0.0-beta.7" />
    <PackageVersion Include="OpenTelemetry.Instrumentation.Http" Version="1.12.0" />
    <PackageVersion Include="OpenTelemetry.Instrumentation.Runtime" Version="1.12.0" />
    <PackageVersion Include="Riok.Mapperly" Version="4.2.1" />
    <PackageVersion Include="Swashbuckle.AspNetCore.Annotations" Version="9.0.4" />
    <PackageVersion Include="Swashbuckle.AspNetCore" Version="9.0.4" />
  </ItemGroup>
</Project>